// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafka.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import kafka.impl.KafkaConsumerRepository;
import kafka.impl.KafkaProcessorRepository;
import kafka.impl.KafkaProducerRepository;

/**
 * Stops all Kafka Consumers, Producers and Processors.
 * 
 * This action will always return true.
 */
public class StopAll extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.Boolean producers;
	private java.lang.Boolean consumers;
	private java.lang.Boolean processors;

	public StopAll(IContext context, java.lang.Boolean producers, java.lang.Boolean consumers, java.lang.Boolean processors)
	{
		super(context);
		this.producers = producers;
		this.consumers = consumers;
		this.processors = processors;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (producers)
			KafkaProducerRepository.closeAll();
		if (consumers)
			KafkaConsumerRepository.stopAll();
		if (processors)
			KafkaProcessorRepository.closeAll();
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StopAll";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
